---
resources:
- name: app-repo
  type: git
  source:
    uri: git@github.com:edtan/concourse-semver-pipeline.git
    private_key: ((github-private-key))
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:edtan/concourse-semver-pipeline.git
    branch: version
    private_key: ((github-private-key))
    file: version
    git_user: ConcourseCI <ci@techorrect.com>
- name: github-release
  type: github-release
  source:
    owner: edtan
    repository: concourse-semver-pipeline
    access_token: ((github-access-token))

jobs:
- name: build
  serial: true
  plan:
  - aggregate:
    - get: app-repo
      trigger: true
    - get: version
      params:
        pre: rc
  - task: Build application
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
        - name: app-repo
        - name: version
      run:
        path: sh
        args:
          - -exc
          - |
            sha=$(cat app-repo/.git/ref)
            ver=$(cat version/version)
            echo "# v${ver} Release Notes" > results/notes.md
            echo "This is version ${ver} of the app, based on ${sha}" > results/app-v${ver}.txt
      outputs:
        - name: results
  - put: version
    params: {file: version/version}
  - put: github-release
    params:
      name: version/version
      tag: version/version
      body: results/notes.md
      commitish: app-repo/.git/ref
      globs:
      - results/app-v*.txt
